name: Notify n8n

on:
  push:
    paths:
      - '**/*.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to n8n
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.N8N_WEBHOOK_URL }}
          method: 'POST'
          contentType: 'application/json'
          body: |
            {
              "ref": "${{ github.ref }}",
              "files": ${{ toJson(github.event.commits.*.modified) }}
            }